name: Build and package NewLauncher

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12

      - name: Give gradlew execute permissions
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Install jpackage dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y fakeroot dpkg-dev

      - name: Install WiX Toolset (Windows)
        if: runner.os == 'Windows'
        run: choco install wixtoolset -y

      - name: Build project with Gradle
        run: ./gradlew clean shadowJar jpackage

      - name: Upload jar (shadowJar)
        uses: actions/upload-artifact@v4
        with:
          name: jar-${{ matrix.os }}
          path: build/libs/*.jar

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}
          path: build/jpackage/*.{msi,deb,dmg,pkg,rpm,exe}
