name: Build and package NewLauncher

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10

      - name: Give gradlew execute permissions
        run: chmod +x gradlew

      - name: Build project with Gradle
        run: ./gradlew clean shadowJar jpackageWindows jpackageMac jpackageLinux

      - name: Upload Windows package
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: build/jpackage/*

      - name: Upload macOS package
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-package
          path: build/jpackage/*

      - name: Upload Linux package
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-package
          path: build/jpackage/*
